FROM fluent/fluentd:v1.14-1

COPY ./fluent.conf /fluentd/etc/fluent.conf
VOLUME ./fluentd/logs:/fluentd/log


USER root

RUN sh -c "apk update \
    && apk add gcc make ruby-dev \
    && fluent-gem install fluent-plugin-kafka --no-document"

USER fluent

EXPOSE 24224
