version: "3"
  

networks:
  dp:
    driver: bridge

services:
  fluentd:
    container_name: fluentd
    build:
      context: fluentd
      dockerfile: Dockerfile.fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./fluentd/logs:/fluentd/log
    ports:
      - "24224:24224"
    networks:
      - dp
